### ISSUE TITLE
AV on fast mouse scroll on property values (ACol = 1)

### ISSUE THREAD

**Issue by attikov** [marcocantu/ObjectDebugger#12]
in TCantObjDebForm.sgPropSelectCell

"EditNum.Text :=" and "EditStr.Text :=" (TEdits) has to be backed up with disabling the onchange event as it will set EditModified to true
and it allways will write back on onexit. But under fast scrolling the component could be already changed and it will try to write back into the wrong place. Mostly causing an AV.

under "tkInteger:"

            EditNum.OnChange := nil;
            try
              EditNum.Text := GetPropValAsString(CurrComp, ppInfo);
              PlaceControl(EditNum);
            finally
              EditNum.OnChange := EditChange;
            end;

and under "tkString, tkLString, tkUString, tkWString:"

          EditStr.OnChange := nil;
          try
            EditStr.Text := GetPropValAsString(CurrComp, ppInfo);
            PlaceControl(EditStr);
          finally
            EditStr.OnChange := EditChange;
          end;

(The other edit controls are fine for now, but it would be even better to introduce an "FInternalUpdating" variable and check against in the OnChange events before setting "EditModified" to true.)

Also "EditModified := False;" is not set everywhere, so it shuld be pesent only one time, right after the case block at the end of "sgPropSelectCell".

I think I have already reported this back in the G+ era.

**Comment by marcocantu** [comment]
Fixed
