### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by talpa** [marcocantu/ObjectDebugger#2]
have you please any easy manual or howto? 

Thanks

Ales

**Comment by marcocantu** [comment]
No, only a short description in a blog post

On Thu, Mar 10, 2016 at 11:40 PM, talpa notifications@github.com wrote:

> have you please any easy manual or howto?
> 
> Thanks
> 
> Ales
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcocantu/ObjectDebugger/issues/2.

## 

-Marco Cantù
RAD Studio Product Manager
