### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by limelect** [marcocantu/ObjectDebugger#8]
above 
var 
CantObjectDebugger:TCantObjectDebugger;

I made a very simple project with one line ONCREATE
 CantObjectDebugger:=TCantObjectDebugger.Create(Form1);
CantObjectDebugger.active:=true;

I get with D10.2.3 access violation.
I close the error and see the object. As a matter of fact, it is shown before the error than the error.
I could not pinpoint the bug although the object inspector is shown.
I got so far as UpdateCompsCombo end and no error.
The timer is OK too.
Could not find nil somewhere.
end of FormShow(Sender: TObject); no error.

**Comment by marcocantu** [comment]
I've just published a new version that should work. One of the event handler parameters wasn't compatible any more

**Comment by marcocantu** [comment]
Check the latest version
